;/*FB_PKG_DELIM*/

__d("isRelativeURL",[],(function(a,b,c,d,e,f){"use strict";var g=/^(#|\/\w)/;function a(a){return g.test(a)}f["default"]=a}),66);
__d("addAnnotations",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){Object.keys(b).forEach(function(c){var d;a[c]=Object.assign((d=a[c])!=null?d:{},b[c])})}f["default"]=a}),66);
__d("JSResource",["JSResourceReferenceImpl"],(function(a,b,c,d,e,f,g){var h={};function i(a,b){h[a]=b}function j(a){return h[a]}function a(a){a=a;var b=j(a);if(b)return b;b=new(c("JSResourceReferenceImpl"))(a);i(a,b);return b}a.loadAll=c("JSResourceReferenceImpl").loadAll;g["default"]=a}),98);
__d("JSResourceForInteraction",["JSResource"],(function(a,b,c,d,e,f,g){function a(a){return c("JSResource").call(null,a)}b=a;g["default"]=b}),98);
__d("generateLiteTypedLogger",["Banzai","JstlMigrationFalcoEvent","getDataWithLoggerOptions"],(function(a,b,c,d,e,f,g){"use strict";function h(a,b,d){var e=a.split(":")[0],f=a.split(":")[1];e=="logger"?c("JstlMigrationFalcoEvent").log(function(){return{logger_config_name:f,payload:b}}):c("Banzai").post(a,b,d)}function a(a){return{log:function(b,d){h(a,c("getDataWithLoggerOptions")(b,d),c("Banzai").BASIC)},logVital:function(b,d){h(a,c("getDataWithLoggerOptions")(b,d),c("Banzai").VITAL)},logImmediately:function(b,d){h(a,c("getDataWithLoggerOptions")(b,d),{signal:!0})}}}g["default"]=a}),98);
__d("ReactDOMComet",["cr:1108857","cr:1294159","cr:734","qex"],(function(a,b,c,d,e,f,g){e=b("cr:734")?b("cr:734")(b("cr:1294159").createPortal):b("cr:1294159").createPortal;function a(a,d){return b("cr:1294159").createRoot(a,babelHelpers["extends"]({},d,{unstable_concurrentUpdatesByDefault:c("qex")._("723")?!1:(a=d==null?void 0:d.unstable_concurrentUpdatesByDefault)!=null?a:!1}))}function d(a,d,e){return b("cr:1294159").hydrateRoot(a,d,babelHelpers["extends"]({onRecoverableError:function(a){if(a!=null&&typeof a.message==="string"){var b=a.message;if(b.indexOf("The server could not finish this Suspense boundary")!==-1||b.indexOf("Minified React error #419;")!==-1||b.indexOf("This Suspense boundary received an update")!==-1||b.indexOf("Minified React error #421;")!==-1)return}typeof reportError==="function"&&reportError(a)}},e,{unstable_concurrentUpdatesByDefault:c("qex")._("723")?!1:(a=e==null?void 0:e.unstable_concurrentUpdatesByDefault)!=null?a:!1}))}g.createPortal=e;g.unstable_batchedUpdates=b("cr:1294159").unstable_batchedUpdates;g.flushSync=b("cr:1294159").flushSync;g.createRoot=a;g.hydrateRoot=d;g.unstable_createEventHandle=b("cr:1294159").unstable_createEventHandle;g.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED=b("cr:1294159").__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;g.version=b("cr:1294159").version}),98);
__d("SchedulerPostTask-dev.classic",[],(function(a,b,c,d,e,f){"use strict"}),null);
__d("SchedulerPostTask-profiling.classic",[],(function(a,b,c,d,e,f){"use strict";b=window.performance;var g=window.setTimeout,h=a.scheduler,i=b.now.bind(b),j=0,k=3;function l(a,b,c,d){j=i()+5;try{k=a;d=d(!1);if("function"===typeof d){var e=new TaskController(),f={priority:b,signal:e.signal};c._controller=e;e=l.bind(null,a,b,c,d);void 0!==h.yield?h.yield(f).then(e)["catch"](m):h.postTask(e,f)["catch"](m)}}catch(a){g(function(){throw a})}finally{k=3}}function m(){}f.unstable_IdlePriority=5;f.unstable_ImmediatePriority=1;f.unstable_LowPriority=4;f.unstable_NormalPriority=3;f.unstable_Profiling=null;f.unstable_UserBlockingPriority=2;f.unstable_cancelCallback=function(a){a._controller.abort()};f.unstable_continueExecution=function(){};f.unstable_forceFrameRate=function(){};f.unstable_getCurrentPriorityLevel=function(){return k};f.unstable_getFirstCallbackNode=function(){return null};f.unstable_next=function(a){switch(k){case 1:case 2:case 3:var b=3;break;default:b=k}var c=k;k=b;try{return a()}finally{k=c}};f.unstable_now=i;f.unstable_pauseExecution=function(){};f.unstable_requestPaint=function(){};f.unstable_runWithPriority=function(a,b){var c=k;k=a;try{return b()}finally{k=c}};f.unstable_scheduleCallback=function(a,b,c){switch(a){case 1:case 2:var d="user-blocking";break;case 4:case 3:d="user-visible";break;case 5:d="background";break;default:d="user-visible"}var e=new TaskController();c={priority:d,delay:"object"===typeof c&&null!==c?c.delay:0,signal:e.signal};e={_controller:e};h.postTask(l.bind(null,a,d,e,b),c)["catch"](m);return e};f.unstable_shouldYield=function(){return i()>=j};f.unstable_wrapCallback=function(a){var b=k;return function(){var c=k;k=b;try{return a()}finally{k=c}}}}),null);
__d("HiddenSubtreePassiveContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({getCurrentState:function(){return{backgrounded:!1,hidden:!1,hiddenOrBackgrounded:!1,hiddenOrBackgrounded_FIXME:!1}},subscribeToChanges:function(a){return{remove:function(){}}}});g["default"]=b}),98);
__d("getTopMostRouteInfo",[],(function(a,b,c,d,e,f){"use strict";function a(a){var b=a.hosted,c=a.main;a=a.pushViewStack;if(a&&a.length>0){a=a[a.length-1];a.depth;a.key;a=babelHelpers.objectWithoutPropertiesLoose(a,["depth","key"]);return a}return b?b:c}f["default"]=a}),66);
__d("goForceFullPageRedirectTo",["ConstUriUtils","FBLogger","err"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){var e=typeof a==="string"?d("ConstUriUtils").getUri(a):d("ConstUriUtils").isConstUri(a);if(e)b===!0?window.location.replace(e.toString()):window.location=e.toString();else{b="Invalid URI "+a.toString()+" provided to goFullPageRedirectTo";c("FBLogger")("comet_infra").blameToPreviousFrame().mustfix(b)}}g["default"]=a}),98);
__d("useUnsafeRef_DEPRECATED",["react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useMemo;function a(a){return h(function(){return{current:a}},[])}g["default"]=a}),98);
__d("testID",["gkx"],(function(a,b,c,d,e,f,g){"use strict";var h=c("gkx")("1070695");function a(a){return h&&a!=null?{"data-testid":a}:void 0}g["default"]=a}),98);