;/*FB_PKG_DELIM*/

__d("CometContextualMessage.react",["fbt","ix","CometIcon.react","CometRow.react","CometRowItem.react","FbtResultBase","TetraTextPairing.react","fbicon","react","stylex"],(function(a,b,c,d,e,f,g,h,i){"use strict";var j=d("react"),k={closeButton:{marginEnd:"xcud41i",marginTop:"x9otpla",$$css:!0},icon:{marginTop:"x1rdy4ex",$$css:!0},root:{borderTopStartRadius:"x1lq5wgf",borderTopEndRadius:"xgqcy7u",borderBottomEndRadius:"x30kzoy",borderBottomStartRadius:"x9jhf4c",overflowX:"x6ikm8r",overflowY:"x10wlt62",paddingTop:"x1iorvi4",paddingEnd:"x150jy0e",paddingBottom:"x1l90r2v",paddingStart:"x1e558r4",$$css:!0}},l={highlight:{backgroundColor:"xwnonoy",$$css:!0},"highlight-bg":{backgroundColor:"xfmpgtx",$$css:!0},primary:{backgroundColor:"x1jx94hy",$$css:!0},secondary:{backgroundColor:"xlhe6ec",$$css:!0}};function a(a,b){var e=a.addOnPrimary,f=a.addOnSecondary,g=a.body,m=a.headline,n=a.headlineLineLimit,o=a.icon,p=a.level;p=p===void 0?3:p;var q=a.meta,r=a.testid;r=a.type;r=r===void 0?"primary":r;var s=a.onClose!=null?a.onClose:null;a=a.headlineAriaLabel!=null?a.headlineAriaLabel:typeof m==="string"||m instanceof c("FbtResultBase")?m:null;return j.jsxs("div",{className:c("stylex")(k.root,l[r]),"data-testid":void 0,ref:b,children:[j.jsxs(c("CometRow.react"),{verticalAlign:"center",children:[o!=null?j.jsx(c("CometRowItem.react"),{verticalAlign:"top",children:j.jsx("div",{className:"x1rdy4ex",children:o})}):null,j.jsx(c("CometRowItem.react"),{expanding:!0,children:j.jsx(c("TetraTextPairing.react"),{body:g,bodyColor:r==="highlight"?"white":"secondary",headline:m,headlineColor:r==="highlight"?"white":"primary",headlineLineLimit:(b=n)!=null?b:2,level:p})}),s!=null?j.jsx(c("CometRowItem.react"),{verticalAlign:"top",children:j.jsx("div",{className:"xcud41i x9otpla",children:j.jsx(c("CometIcon.react"),{"aria-label":a!=null?h._("__JHASH__jdA38No1bHZ__JHASH__",[h._param("card name",a)]):h._("__JHASH__PfdWOKkgwGk__JHASH__"),color:r==="highlight"?"white":"secondary",icon:d("fbicon")._(i("478232"),16),onPress:s,size:16,testid:void 0})})}):null]}),e,f,q!=null&&j.jsx(c("CometRow.react"),{paddingTop:12,children:j.jsx(c("CometRowItem.react"),{children:j.jsx(c("TetraTextPairing.react"),{level:p,meta:q})})})]})}a.displayName=a.name+" [from "+f.id+"]";b=j.forwardRef(a);g["default"]=b}),98);
__d("OptimisticLoadingTypeEnum",[],(function(a,b,c,d,e,f){"use strict";a=Object.freeze({PENDING:"PENDING",SHOW_ANIMATION:"SHOW_ANIMATION",SHOW_LOADER:"SHOW_LOADER",SHOW_POST_PREVIEW:"SHOW_POST_PREVIEW",SHOW_PROGRESS_BAR:"SHOW_PROGRESS_BAR"});f["default"]=a}),66);
__d("CometLexicalContentEditableCommands",["Lexical"],(function(a,b,c,d,e,f,g){"use strict";a=d("Lexical").createCommand();g.COMET_LEXICAL_ARIA_COMMAND=a}),98);
__d("mlcEditableSubscription",[],(function(a,b,c,d,e,f){"use strict";function a(a){return{initialValueFn:function(){return a.isEditable()},subscribe:function(b){return a.registerEditableListener(b)}}}f["default"]=a}),66);
__d("useCometLexicalSubscription",["react","useUnsafeRef_DEPRECATED"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useLayoutEffect,i=b.useState;function a(a){var b=c("useUnsafeRef_DEPRECATED")(a.initialValueFn()),d=i(b.current),e=d[0],f=d[1];h(function(){var c=a.initialValueFn,d=a.subscribe;c=c();b.current!==c&&(b.current=c,f(c));return d(function(a){b.current=a,f(a)})},[a]);return e}g["default"]=a}),98);
__d("CometLexicalContentEditable.react",["CometLexicalContentEditableCommands","Lexical","mlcEditableSubscription","react","stylex","useCometLexicalSubscription"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");b=d("react");var i=b.useEffect,j=b.useLayoutEffect,k=b.useMemo,l=b.useState,m={editor:{color:"xzsf02u",outline:"x1a2a7pz",position:"x1n2onr6",textAlign:"x14wi4xw",$$css:!0}};function a(a){var b=a.ariaAutoComplete,e=a.ariaDescribedBy,f=a.ariaExpanded,g=a.ariaLabel,n=a.ariaLabelledBy,o=a.ariaMultiline,p=a.ariaOwneeID,q=a.ariaRequired,r=a.autoCapitalize,s=a.autoComplete,t=a.autoCorrect,u=a.contentEditableRef,v=a.editor,w=a.isInitiallyFocused,x=w===void 0?!1:w;w=a.role;w=w===void 0?"textbox":w;var y=a.spellCheck;y=y===void 0?!1:y;var z=a.tabIndex,A=a.webDriverTestID;A=a.xstyle;a=l(void 0);var B=a[0],C=a[1];a=l(void 0);var D=a[0],E=a[1];a=c("useCometLexicalSubscription")(k(function(){return c("mlcEditableSubscription")(v)},[v]));j(function(){return v.registerCommand(d("CometLexicalContentEditableCommands").COMET_LEXICAL_ARIA_COMMAND,function(a){Object.prototype.hasOwnProperty.call(a,"activeDescendantID")&&C(a.activeDescendantID);Object.prototype.hasOwnProperty.call(a,"controlsID")&&E(a.controlsID);return!1},d("Lexical").COMMAND_PRIORITY_EDITOR)},[v]);i(function(){x&&v.focus(function(){var a=document.activeElement,b=v.getRootElement();(!(b==null?void 0:b.contains(a))||b!=null||a==null)&&(b==null?void 0:b.focus({preventScroll:!0}))})},[v,x]);return h.jsx("div",{"aria-activedescendant":a?B:null,"aria-autocomplete":a?b:null,"aria-controls":a?D:null,"aria-describedby":e,"aria-expanded":a?w==="combobox"?!!f:null:null,"aria-label":g,"aria-labelledby":n,"aria-multiline":o,"aria-owns":a?p:null,"aria-required":q,autoCapitalize:r,autoComplete:s,autoCorrect:t,className:c("stylex")(m.editor,A)+" "+(a?"notranslate":""),contentEditable:a,"data-testid":void 0,ref:u,role:a?w:null,spellCheck:y,suppressContentEditableWarning:!0,tabIndex:z})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("cometLexicalBaseTheme",[],(function(a,b,c,d,e,f,g){"use strict";a={ltr:"xdpxx8g",rtl:"x1hr2gdg"};b=a;g["default"]=b}),98);
__d("useCometLexicalDragAndDrop",["react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useEffect;function a(a,b){var c=b.onDragEnter,d=b.onDragLeave,e=b.onDragOver,f=b.onDrop,g=b.onPaste;h(function(){if(a!=null)return a.registerRootListener(function(a,b){b!=null&&(c&&b.removeEventListener("dragenter",c),d&&b.removeEventListener("dragleave",d),e&&b.removeEventListener("dragover",e),f&&b.removeEventListener("drop",f,!0),g&&b.removeEventListener("paste",g,!0)),a!==null&&(c&&a.addEventListener("dragenter",c),d&&a.addEventListener("dragleave",d),e&&a.addEventListener("dragover",e),f&&a.addEventListener("drop",f,!0),g&&a.addEventListener("paste",g,!0))})},[a,c,d,e,f,g])}g["default"]=a}),98);
__d("useCometLexicalFileDragAndDrop",["react","useCometLexicalDragAndDrop"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useCallback,i=b.useRef;function a(a){var b=a.editor,d=a.isMimeTypeAcceptable,e=a.onHover,f=e===void 0?function(){}:e;e=a.onSubmit;var g=e===void 0?function(){}:e,j=i(0),k=h(function(a){return Array.from(a).filter(d)},[d]);a=h(function(a){j.current++;var b=a.dataTransfer;if(b==null)return f([],!0);b=k(b.items);b.length>0&&a.preventDefault();return f(b,!0)},[k,f]);e=h(function(a){j.current--;if(j.current===0)return f([],!1)},[f]);var l=h(function(a){var b=a.dataTransfer;if(b==null)return f([],!0);b=k(b.items);b.length>0&&a.preventDefault();return f(b,!0)},[k,f]),m=h(function(a,b){b=k(b.items);b=b.map(function(a){return a.getAsFile()}).filter(Boolean);if(b.length>0){a.stopPropagation();a.preventDefault();return g(b)}else return g([])},[k,g]),n=h(function(a){var b=a.dataTransfer;j.current=0;f([],!1);if(b!=null)return m(a,b);else return g([])},[m,f,g]),o=h(function(a){var b=a.clipboardData;if(b==null)return g([]);var c=b.types;c=c.includes("text/plain")&&c.includes("text/html")||c.includes("text/rtf");return c?g([]):m(a,b)},[m,g]);c("useCometLexicalDragAndDrop")(b,{onDragEnter:a,onDragLeave:e,onDragOver:l,onDrop:n,onPaste:o})}g["default"]=a}),98);
__d("CometLexicalEntityTextNode",["Lexical","unrecoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h=function(b){babelHelpers.inheritsLoose(a,b);function a(){return b.apply(this,arguments)||this}var d=a.prototype;d.getEntity=function(){throw c("unrecoverableViolation")("CometLexicalEntityTextNode does not implement getEntity","ufi2")};return a}(d("Lexical").TextNode);function a(a){return a instanceof h}g.CometLexicalEntityTextNode=h;g.isCometLexicalEntityTextNode=a}),98);
__d("CometLexicalDelightNode",["CometLexicalEntityTextNode"],(function(a,b,c,d,e,f,g){"use strict";var h=function(b){babelHelpers.inheritsLoose(a,b);a.getType=function(){return"delight"};a.clone=function(b){return new a(b.__text,b.__styles,b.__campaignID,b.__delightAsset,b.__key)};a.importJSON=function(a){return i(a.text,a.styles,a.campaignID,a.delightAsset)};var c=a.prototype;c.exportJSON=function(){return babelHelpers["extends"]({},b.prototype.exportJSON.call(this),{campaignID:this.__campaignID,delightAsset:this.__delightAsset,styles:this.__styles,type:"delight",version:1})};function a(a,c,d,e,f){a=b.call(this,a,f)||this;a.__entityType="TextDelightCampaign";a.__styles=c;a.__campaignID=d;a.__delightAsset=e;return a}c.createDOM=function(a){a=b.prototype.createDOM.call(this,a);var c=this.__delightAsset.id,d=this.__styles,e=d.color;d=d["font-weight"];c!=null&&a.setAttribute("data-delight-asset",c);a.setAttribute("data-delight","true");e!=null&&d!=null&&(a.style.color=e,a.style.fontWeight=d);return a};c.getEntity=function(){return{__UFI__:!0,id:this.__campaignID,isWeak:!1,type:this.__entityType}};c.canInsertTextBefore=function(){return!1};c.canInsertTextAfter=function(){return!1};return a}(d("CometLexicalEntityTextNode").CometLexicalEntityTextNode);function i(a,b,c,d){return new h(a,b,c,d)}function a(a){return a instanceof h}g.CometLexicalDelightNode=h;g.$createLexicalDelightNode=i;g.$isLexicalDelightNode=a}),98);
__d("CometLexicalEmojiNode",["Lexical"],(function(a,b,c,d,e,f,g){"use strict";var h=9;b=16;c=20;var i=16,j=function(b){babelHelpers.inheritsLoose(a,b);a.getType=function(){return"emoji"};a.clone=function(b){return new a(b.__text,b.__rawText,b.__src,b.__size,b.__key)};a.importJSON=function(a){a=k(a.text,a.rawText,a.src,a.size);return a};var c=a.prototype;c.exportJSON=function(){return babelHelpers["extends"]({},b.prototype.exportJSON.call(this),{rawText:this.__rawText,size:this.__size,src:this.__src,type:"emoji"})};function a(a,c,d,e,f){e===void 0&&(e=i);a=b.call(this,a,f)||this;a.__src=d;a.__rawText=c;a.__size=e;return a}c.getRawText=function(){var a=this.getLatest();return a.__rawText};c.createDOM=function(){var a=this.__text,b=this.__size,c=this.__src,d=document.createElement("span"),e=document.createElement("span"),f=d.style;f.cursor="default";d.className="x1xsqp64 xiy17q3 x1o6pynw x19co3pv xdj266r xcwd3tp xat24cr x39eecv x2b8uid";d.setAttribute("data-testid","emoji");c!=null&&(f.backgroundImage="url("+c+")",f.backgroundSize=b+"px "+b+"px");a!==this.__rawText&&(d.style.width="calc("+b+"px + 0.3em)",d.style.height=b+"px",d.className="x1xsqp64 xiy17q3 x1o6pynw x19co3pv xdj266r xcwd3tp xat24cr x39eecv x2b8uid x1rg5ohu x6ikm8r x10wlt62 xmziwt1 xuxw1ft",d.setAttribute("spellcheck","false"),e.style.fontFamily='Courier, "Courier New", Menlo, Monaco, monospace',e.style.fontSize="15px",e.style.letterSpacing=b/(h*a.length)-1+"ch");e.textContent=a;e.className="xexx8yu xn5pp95 x18d9i69 x2fxd7x x1yqt14a x1bhl96m";d.appendChild(e);return d};c.updateDOM=function(a,b){a=b.firstChild;if(a==null)return!0;var c=this.__text;a.textContent!==c&&(a.textContent=c);b.style.backgroundSize=this.__size+"px "+this.__size+"px";return!1};c.setSize=function(a){var b=this.getWritable();b.__size=a};c.selectionTransform=function(a,b){var c=this.__text;if(c===this.__rawText||!d("Lexical").$isRangeSelection(a)||a.is(b))return;a=a.focus;var e=b.focus,f=c.length,g=b.isCollapsed();if(e.offset===0||e.offset===c.length||a.is(e))return;a.isBefore(e)?e.set(e.key,f,"text"):e.set(e.key,0,"text");g&&b.anchor.set(e.key,e.offset,"text")};return a}(d("Lexical").TextNode);function a(a){return a instanceof j}function k(a,b,c,d){return new j(a,b,c,d).setMode("token")}g.UFI_EMOJI_SIZE=b;g.COMPOSER_EMOJI_SIZE_LARGE=c;g.COMPOSER_EMOJI_SIZE_SMALL=i;g.EmojiNode=j;g.$isEmojiNode=a;g.$createEmojiNode=k}),98);
__d("CometLexicalGenericEntityNode",["CometLexicalEntityTextNode"],(function(a,b,c,d,e,f,g){"use strict";var h=function(b){babelHelpers.inheritsLoose(a,b);a.getType=function(){return"actor"};a.clone=function(b){var c;return new a({id:b.__id,text:b.__text,type:b.__entityType,uri:(c=b.__uri)!=null?c:void 0},b.__key)};a.importJSON=function(a){return i({id:a.id,text:a.text,type:a.entityType,uri:(a=a.uri)!=null?a:void 0})};var c=a.prototype;c.exportJSON=function(){return babelHelpers["extends"]({},b.prototype.exportJSON.call(this),{entityType:this.__entityType,id:this.__id,type:"actor",uri:this.__uri})};function a(a,c){var d="",e="Actor",f=void 0,g="";a!==void 0&&(d=a.id,e=a.type,f=a.uri,g=a.text);a=b.call(this,g,c)||this;a.__id=d;a.__entityType=e;a.__uri=f;return a}c.createDOM=function(a){a=b.prototype.createDOM.call(this,a);a.className="xv78j7m";a.spellcheck=!1;return a};c.getEntity=function(){var a=this.__uri!=null?{uri:this.__uri}:null;return babelHelpers["extends"]({__UFI__:!0,id:this.__id,isWeak:!1,type:this.__entityType},a)};c.getEntityType=function(){return this.__entityType};c.getID=function(){return this.__id};return a}(d("CometLexicalEntityTextNode").CometLexicalEntityTextNode);function i(a){return new h(a).setMode("segmented").toggleDirectionless()}function a(a){return a instanceof h}g.CometLexicalGenericEntityNode=h;g.$createCometLexicalGenericEntityNode=i;g.$isCometLexicalGenericEntityNode=a}),98);
__d("CometLexicalPlaceholder.react",["react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i={placeholder:{color:"xi81zsa",overflowX:"x6ikm8r",overflowY:"x10wlt62",pointerEvents:"x47corl",position:"x10l6tqk",start:"x17qophe",textOverflow:"xlyipyv",top:"x13vifvy",userSelect:"x87ps6o",whiteSpace:"xuxw1ft",width:"xh8yej3",$$css:!0}};function a(a){var b=a.children;a=a.xstyle;return h.jsx("div",{children:b,className:c("stylex")(i.placeholder,a)})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("useDeferredModuleOnReady",["react"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useEffect,i=b.useState;function a(b){var c=i(function(){return b.getModuleIfRequireable()}),a=c[0],d=c[1];h(function(){if(a!=null)return;var c=b.onReady(function(a){d(function(){return a})});return function(){c.remove()}},[b,a]);return a}g["default"]=a}),98);
__d("CometDelightsPluginForLexical",["react","requireDeferred","useDeferredModuleOnReady"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=c("requireDeferred")("UpgradedCometDelightsPluginForLexical").__setRef("CometDelightsPluginForLexical");function a(a){a=a.pluginProps;a=a.editor;var b=c("useDeferredModuleOnReady")(i);return b!=null?h.jsx(b,{editor:a}):null}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("cometIsMimeTypeForMedia",["FBLogger","UFICommentFileInputAcceptValues"],(function(a,b,c,d,e,f,g){"use strict";var h={file:null,photo:null,video:null},i={"image/gif":"video","image/webp":"video"};function j(a){return a.split(",").map(function(a){return a.trim()}).map(function(a){return a.replace(/\/\*$/,"/")})}function k(a,b,d){h[a]==null&&(h[a]=j(d));d=h[a];if(d==null)throw c("FBLogger")("ufi2").mustfixThrow("CometIsMimeTypeForMedia prefixes can't be null");var e=i[b];return e!=null?e===a:d.some(function(a){return b.startsWith(a)})}function a(a){return k("photo",a,d("UFICommentFileInputAcceptValues").photos)}function b(a){return k("video",a,d("UFICommentFileInputAcceptValues").videos)}function e(a){return k("file",a,d("UFICommentFileInputAcceptValues").files)}g.mimeTypeAcceptStringToArray=j;g.isMimeTypeForPhoto=a;g.isMimeTypeForVideo=b;g.isMimeTypeForFile=e}),98);
__d("LexicalComposerContext",["cr:509"],(function(a,b,c,d,e,f){e.exports=b("cr:509")}),null);
__d("MLCCharacterLimitCountPlugin.react",["LexicalComposerContext","LexicalText","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useEffect,i=function(a){return a.length};function a(a){var b=a.editor__DEPRECATED,c=a.limit,e=a.strlen,f=e===void 0?i:e,g=a.onChange,j;if(b)j=b;else{e=d("LexicalComposerContext").useLexicalComposerContext();j=e[0]}h(function(){var a=j.getEditorState().read(function(){return c-f(d("LexicalText").$rootTextContent())});g(a);return j.registerTextContentListener(function(a){a=c-f(a);g(a)})},[j,c,g,f]);return null}g["default"]=a}),98);
__d("MLCInstrumentationCommands",["Lexical"],(function(a,b,c,d,e,f,g){"use strict";a=d("Lexical").createCommand();b=d("Lexical").createCommand();c=d("Lexical").createCommand();e=d("Lexical").createCommand();g.COMMIT_COMMAND=a;g.INTERACTION_INSTRUMENTATION_READY=b;g.DOCUMENT_COMMAND=c;g.PLUGIN_EVENT_COMMAND=e}),98);
__d("MLCInstrumentationPluginDeferred__INTERNAL.react",["react","requireDeferred","useDeferredModuleOnReady"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=c("requireDeferred")("MLCInstrumentationPlugin__INTERNAL.react").__setRef("MLCInstrumentationPluginDeferred__INTERNAL.react");function a(a){var b=c("useDeferredModuleOnReady")(i);return b==null?null:h.jsx(b,babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("mlcErrorHandler__INTERNAL",["Lexical"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b,c){var d=document.activeElement,e=null;d!=null&&(e={activeElement:d.nodeName,rootSelected:d===b.getRootElement()});d=window.event;var f=null;d!=null&&(f={altKey:d.altKey,ctrlKey:d.ctrlKey,data:d.data,inputType:d.inputType,isComposing:d.isComposing,keyCode:d.keyCode,metaKey:d.metaKey,shiftKey:d.shiftKey,type:d.type});d=null;try{d=h(b.getEditorState())}catch(a){}c(JSON.stringify({activeElement:e,editorState:d,error:a,event:f}))}function h(a){return{nodes:i(a),selection:k(a)}}function i(a){var b=[],c=["key","type","detail","format","mode","children","parent","first","last","size","next","prev"];for(var a=a._nodeMap,d=Array.isArray(a),e=0,a=d?a:a[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var f;if(d){if(e>=a.length)break;f=a[e++]}else{e=a.next();if(e.done)break;f=e.value}f=f;f[0];f=f[1];var g={};for(var h=0;h<c.length;h++){var i=c[h],k="__"+i;k=f[k];if(k==null||j(i,k))continue;g[i]=k}b.push(g)}return b}function j(a,b){var c=new Set(["detail","format"]);if(c.has(a)&&b===0)return!0;return a==="mode"&&b==="normal"?!0:!1}function k(a){a=a._selection;if(!d("Lexical").$isRangeSelection(a))return null;var b=a.anchor;a=a.focus;return{anchor:{key:b.key,offset:b.offset,type:b.type},focus:{key:a.key,offset:a.offset,type:a.type}}}g["default"]=a}),98);
__d("useLexicalInitializeEditor__DEPRECATED",["Lexical","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useLayoutEffect;function a(a){h(function(){a.update(function(){var b=d("Lexical").$getRoot();if(b.isEmpty()){var c=d("Lexical").$createParagraphNode();b.append(c);b=document.activeElement;(d("Lexical").$getSelection()!==null||b!==null&&b===a.getRootElement())&&c.select()}})},[a])}g["default"]=a}),98);
__d("UFI2ScaleRect",["invariant"],(function(a,b,c,d,e,f,g,h){"use strict";function a(a){return i(a,!0)}function b(a){return i(a,!1)}function i(a,b){var c=a.srcHeight,d=a.srcWidth,e=a.maxHeight,f=a.maxWidth;a=a.gracefullyFallbackToMaxDimensionWhenHeightOrWidthIsZero;!1===a&&(c>0||h(0,5272,c),d>0||h(0,5273,d));e>0||h(0,5274,e);f>0||h(0,5275,f);c=a&&c===0?e:c;a=a&&d===0?f:d;d=f/a;f=e/c;e=b?Math.min(d,f):Math.min(d,f,1);return{height:Math.round(c*e),width:Math.round(a*e)}}g.scaleToContain=a;g.shrinkToContain=b}),98);
__d("nodeIsInConnection",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){a=a.getLinkedRecords("edges");if(a==null){c&&c("Connection contains no edges field.");return!1}var d=!1;b=b.getDataID();if(b==null){c&&c("Search node has no ID.");return!1}for(var e=a,f=Array.isArray(e),g=0,e=f?e:e[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var h;if(f){if(g>=e.length)break;h=e[g++]}else{g=e.next();if(g.done)break;h=g.value}h=h;var i=h&&h.getLinkedRecord("node");if(i==null){c&&c("Edge at index "+a.indexOf(h)+" has no node.");continue}if(i.getDataID()===b){d=!0;break}}return d}f["default"]=a}),66);
__d("LexicalClipboard",["cr:862"],(function(a,b,c,d,e,f){e.exports=b("cr:862")}),null);
__d("LexicalHtml",["cr:1497"],(function(a,b,c,d,e,f){e.exports=b("cr:1497")}),null);
__d("LexicalSelection",["cr:2180"],(function(a,b,c,d,e,f){e.exports=b("cr:2180")}),null);
__d("LexicalUtils",["cr:2774"],(function(a,b,c,d,e,f){e.exports=b("cr:2774")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalClipboard.prod",["Lexical","LexicalHtml","LexicalSelection","LexicalUtils","Promise","regeneratorRuntime"],(function $module_LexicalClipboard_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";function z(a){var b=new URLSearchParams();b.append("code",a);for(var c=1;c<arguments.length;c++){b.append("v",arguments[c]);}throw Error("Minified Lexical error #"+a+"; visit https://lexical.dev/docs/error?"+b+" for the full message or "+"use the non-minified dev environment for full errors and additional helpful warnings.");}
var A="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement;function B(a){var b=require("Lexical").$getSelection();if(null==b)throw Error("Expected valid LexicalSelection");return require("Lexical").$isRangeSelection(b)&&b.isCollapsed()||0===b.getNodes().length?"":require("LexicalHtml").$generateHtmlFromNodes(a,b);}
function C(a){var b=require("Lexical").$getSelection();if(null==b)throw Error("Expected valid LexicalSelection");return require("Lexical").$isRangeSelection(b)&&b.isCollapsed()||0===b.getNodes().length?null:JSON.stringify(D(a,b));}function E(a,b,c){(require("Lexical").DEPRECATED_$isGridSelection(c)||null!==require("LexicalUtils").$findMatchingParent(c.anchor.getNode(),function(e){return require("Lexical").DEPRECATED_$isGridCellNode(e);})&&null!==require("LexicalUtils").$findMatchingParent(c.focus.getNode(),function(e){return require("Lexical").DEPRECATED_$isGridCellNode(e);}))&&1===b.length&&require("Lexical").DEPRECATED_$isGridNode(b[0])?F(b,c,!1,a):I(b,c);}
function I(a,b){var _a;var c=[],e=null;for(var f=0;f<a.length;f++){var h=a[f],g=require("Lexical").$isLineBreakNode(h);if(g||require("Lexical").$isDecoratorNode(h)&&h.isInline()||require("Lexical").$isElementNode(h)&&h.isInline()||require("Lexical").$isTextNode(h)||h.isParentRequired()){if(null===e&&(e=h.createParentElementNode(),c.push(e),g))continue;null!==e&&e.append(h);}else c.push(h),e=null;}require("Lexical").$isRangeSelection(b)?b.insertNodes(c):require("Lexical").DEPRECATED_$isGridSelection(b)&&(a=b.anchor.getNode(),require("Lexical").DEPRECATED_$isGridCellNode(a)||z(41),(_a=a).append.apply(_a,c));}
function F(a,b,c,e){1===a.length&&require("Lexical").DEPRECATED_$isGridNode(a[0])||z(42);var f=a[0];a=f.getChildren();c=f.getFirstChildOrThrow().getChildrenSize();var h=f.getChildrenSize(),g=require("LexicalUtils").$findMatchingParent(b.anchor.getNode(),function(l){return require("Lexical").DEPRECATED_$isGridCellNode(l);});b=(f=g&&require("LexicalUtils").$findMatchingParent(g,function(l){return require("Lexical").DEPRECATED_$isGridRowNode(l);}))&&require("LexicalUtils").$findMatchingParent(f,function(l){return require("Lexical").DEPRECATED_$isGridNode(l);});require("Lexical").DEPRECATED_$isGridCellNode(g)&&require("Lexical").DEPRECATED_$isGridRowNode(f)&&require("Lexical").DEPRECATED_$isGridNode(b)||z(43);var k=f.getIndexWithinParent(),
m=Math.min(b.getChildrenSize()-1,k+h-1);h=g.getIndexWithinParent();g=Math.min(f.getChildrenSize()-1,h+c-1);c=Math.min(h,g);f=Math.min(k,m);h=Math.max(h,g);k=Math.max(k,m);m=b.getChildren();g=0;var n,q;for(var l=f;l<=k;l++){var t=m[l];require("Lexical").DEPRECATED_$isGridRowNode(t)||z(24);var y=a[g];require("Lexical").DEPRECATED_$isGridRowNode(y)||z(24);t=t.getChildren();y=y.getChildren();var G=0;var _loop=function _loop(v){var w=t[v];require("Lexical").DEPRECATED_$isGridCellNode(w)||z(25);var H=y[G];require("Lexical").DEPRECATED_$isGridCellNode(H)||z(25);l===f&&v===c?n=
w.getKey():l===k&&v===h&&(q=w.getKey());var N=w.getChildren();H.getChildren().forEach(function(x){require("Lexical").$isTextNode(x)&&require("Lexical").$createParagraphNode().append(x);w.append(x);});N.forEach(function(x){return x.remove();});G++;};for(var v=c;v<=h;v++){_loop(v);}g++;}n&&q&&(a=require("Lexical").DEPRECATED_$createGridSelection(),a.set(b.getKey(),n,q),require("Lexical").$setSelection(a),e.dispatchCommand(require("Lexical").SELECTION_CHANGE_COMMAND,void 0));}
function J(a,b,c,e){if(e===void 0){e=[];}var f=null!=b?c.isSelected(b):!0,h=require("Lexical").$isElementNode(c)&&c.excludeFromCopy("html");var g=c;if(null!==b){var k=require("LexicalSelection").$cloneWithProperties(c);g=k=require("Lexical").$isTextNode(k)&&null!=b?require("LexicalSelection").$sliceSelectedTextNodeContent(b,k):k;}var m=require("Lexical").$isElementNode(g)?g.getChildren():[];var n=g;k=n.exportJSON();var q=n.constructor;k.type!==q.getType()&&z(58,q.name);var t=k.children;require("Lexical").$isElementNode(n)&&(Array.isArray(t)||z(59,q.name));require("Lexical").$isTextNode(g)&&(g=g.__text,0<g.length?k.text=g:f=!1);for(g=0;g<m.length;g++){n=
m[g],q=J(a,b,n,k.children),!f&&require("Lexical").$isElementNode(c)&&q&&c.extractWithChild(n,b,"clone")&&(f=!0);}if(f&&!h)e.push(k);else if(Array.isArray(k.children))for(a=0;a<k.children.length;a++){e.push(k.children[a]);}return f;}function D(a,b){var c=[],e=require("Lexical").$getRoot().getChildren();for(var f=0;f<e.length;f++){J(a,b,e[f],c);}return{namespace:a._config.namespace,nodes:c};}function K(a){var b=[];for(var c=0;c<a.length;c++){var e=require("Lexical").$parseSerializedNode(a[c]);require("Lexical").$isTextNode(e)&&require("LexicalSelection").$addNodeStyle(e);b.push(e);}return b;}var L=null;
function M(a,b){var c=A?(a._window||window).getSelection():null;if(!c)return!1;var e=c.anchorNode;c=c.focusNode;if(null!==e&&null!==c&&!require("Lexical").isSelectionWithinEditor(a,e,c))return!1;b.preventDefault();b=b.clipboardData;e=require("Lexical").$getSelection();if(null===b||null===e)return!1;c=B(a);a=C(a);var f="";null!==e&&(f=e.getTextContent());null!==c&&b.setData("text/html",c);null!==a&&b.setData("application/x-lexical-editor",a);b.setData("text/plain",f);return!0;}exports.$generateJSONFromSelectedNodes=D;
exports.$generateNodesFromSerializedNodes=K;exports.$getHtmlContent=B;exports.$getLexicalContent=C;exports.$insertDataTransferForPlainText=function(a,b){a=a.getData("text/plain")||a.getData("text/uri-list");null!=a&&b.insertRawText(a);};
exports.$insertDataTransferForRichText=function(a,b,c){var e=a.getData("application/x-lexical-editor");if(e)try{var g=JSON.parse(e);if(g.namespace===c._config.namespace&&Array.isArray(g.nodes)){var k=K(g.nodes);return E(c,k,b);}}catch(_unused){}if(e=a.getData("text/html"))try{var f=new DOMParser().parseFromString(e,"text/html"),h=require("LexicalHtml").$generateNodesFromDOM(c,f);return E(c,h,b);}catch(_unused2){}a=a.getData("text/plain")||a.getData("text/uri-list");if(null!=a)if(require("Lexical").$isRangeSelection(b))for(a=a.split(/(\r?\n|\t)/),c=a.length,
f=0;f<c;f++){h=a[f],"\n"===h||"\r\n"===h?b.insertParagraph():"\t"===h?b.insertNodes([require("Lexical").$createTabNode()]):b.insertText(h);}else b.insertRawText(a);};exports.$insertGeneratedNodes=E;
exports.copyToClipboard=function _callee(a,b){var c,e,f,h;return require("regeneratorRuntime").async(function _callee$(_context){while(1){switch(_context.prev=_context.next){case 0:if(!(null!==L)){_context.next=2;break;}return _context.abrupt("return",!1);case 2:if(!(null!==b)){_context.next=4;break;}return _context.abrupt("return",new(require("Promise"))(function(g){a.update(function(){g(M(a,b));});}));case 4:c=a.getRootElement();e=null==a._window?window.document:a._window.document,f=A?(a._window||window).getSelection():null;if(!(null===c||null===f)){_context.next=8;break;}return _context.abrupt("return",!1);case 8:h=e.createElement("span");h.style.cssText="position: fixed; top: -1000px;";h.append(e.createTextNode("#"));c.append(h);c=new Range();c.setStart(h,0);c.setEnd(h,1);f.removeAllRanges();f.addRange(c);return _context.abrupt("return",new(require("Promise"))(function(g)
{var k=a.registerCommand(require("Lexical").COPY_COMMAND,function(m){require("LexicalUtils").objectKlassEquals(m,ClipboardEvent)&&(k(),null!==L&&(window.clearTimeout(L),L=null),g(M(a,m)));return!0;},require("Lexical").COMMAND_PRIORITY_CRITICAL);L=window.setTimeout(function(){k();L=null;g(!1);},50);e.execCommand("copy");h.remove();}));case 18:case"end":return _context.stop();}}},null,this);};}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalComposerContext.prod",["react"],(function $module_LexicalComposerContext_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var c_react;var d=c_react||(c_react=require("react"));function e(a){var c=new URLSearchParams();c.append("code",a);for(var b=1;b<arguments.length;b++){c.append("v",arguments[b]);}throw Error("Minified Lexical error #"+a+"; visit https://lexical.dev/docs/error?"+c+" for the full message or "+"use the non-minified dev environment for full errors and additional helpful warnings.");}var f=d.createContext(null);exports.LexicalComposerContext=f;
exports.createLexicalComposerContext=function(a,c){var b=null;null!=a&&(b=a[1]);return{getTheme:function getTheme(){return null!=c?c:null!=b?b.getTheme():null;}};};exports.useLexicalComposerContext=function(){var a=d.useContext(f);null==a&&e(8);return a;};}),null);
__d("LexicalDragon",["cr:2903"],(function(a,b,c,d,e,f){e.exports=b("cr:2903")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalDragon.prod",["Lexical"],(function $module_LexicalDragon_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";
exports.registerDragonSupport=function(m){var t=window.location.origin,r=function r(l){if(l.origin===t){var h=m.getRootElement();if(document.activeElement===h&&(h=l.data,"string"===typeof h)){try{var a=JSON.parse(h);}catch(k){return;}if(a&&"nuanria_messaging"===a.protocol&&"request"===a.type&&(a=a.payload)&&"makeChanges"===a.functionId&&(a=a.args)){var _a=a,k=_a[0],n=_a[1],p=_a[2],q=_a[3],u=_a[4];m.update(function(){var f=require("Lexical").$getSelection();if(require("Lexical").$isRangeSelection(f)){var e=f.anchor;var b=e.getNode(),c=0,d=0;require("Lexical").$isTextNode(b)&&0<=k&&0<=n&&(c=k,
d=k+n,f.setTextNodeRange(b,c,b,d));if(c!==d||""!==p)f.insertRawText(p),b=e.getNode();require("Lexical").$isTextNode(b)&&(c=q,d=q+u,e=b.getTextContentSize(),c=c>e?e:c,d=d>e?e:d,f.setTextNodeRange(b,c,b,d));l.stopImmediatePropagation();}});}}}};window.addEventListener("message",r,!0);return function(){window.removeEventListener("message",r,!0);};};}),null);
__d("LexicalErrorBoundary",["cr:2260"],(function(a,b,c,d,e,f){e.exports=b("cr:2260")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalErrorBoundary.prod",["react"],(function $module_LexicalErrorBoundary_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var c_react;var h=c_react||(c_react=require("react"));function m(b,c){m=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(g,a){g.__proto__=a;return g;};return m(b,c);}function n(b,c){b.prototype=Object.create(c.prototype);b.prototype.constructor=b;m(b,c);}function r(b,c){void 0===b&&(b=[]);void 0===c&&(c=[]);return b.length!==c.length||b.some(function(g,a){return!Object.is(g,c[a]);});}
var t={error:null},u=function(b){function c(){for(var a,d=arguments.length,f=Array(d),e=0;e<d;e++){f[e]=arguments[e];}a=b.call.apply(b,[this].concat(f))||this;a.state=t;a.resetErrorBoundary=function(){for(var k,p=arguments.length,q=Array(p),l=0;l<p;l++){q[l]=arguments[l];}null==a.props.onReset?void 0:(k=a.props).onReset.apply(k,q);a.reset();};return a;}n(c,b);c.getDerivedStateFromError=function(a){return{error:a};};var g=c.prototype;g.reset=function(){this.setState(t);};g.componentDidCatch=function(a,d){var f,
e;null==(f=(e=this.props).onError)?void 0:f.call(e,a,d);};g.componentDidUpdate=function(a,d){var f=this.props.resetKeys;if(null!==this.state.error&&null!==d.error&&r(a.resetKeys,f)){var e,k;null==(e=(k=this.props).onResetKeysChange)?void 0:e.call(k,a.resetKeys,f);this.reset();}};g.render=function(){var a=this.state.error,d=this.props,f=d.fallbackRender,e=d.FallbackComponent;d=d.fallback;if(null!==a){a={error:a,resetErrorBoundary:this.resetErrorBoundary};if(h.isValidElement(d))return d;if("function"===
typeof f)return f(a);if(e)return h.createElement(e,a);throw Error("react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop");}return this.props.children;};return c;}(h.Component);module.exports=function(_ref){var b=_ref.children,c=_ref.onError;return h.createElement(u,{fallback:h.createElement("div",{style:{border:"1px solid #f00",color:"#f00",padding:"8px"}},"An error was thrown."),onError:c},b);};}),null);
__d("LexicalHashtag",["cr:2139"],(function(a,b,c,d,e,f){e.exports=b("cr:2139")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalHashtag.prod",["Lexical","LexicalUtils"],(function $module_LexicalHashtag_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var
e=function(_d$TextNode){babelHelpers.inheritsLoose(e,_d$TextNode);e.getType=function getType(){return"hashtag";};e.clone=function clone(a){return new e(a.__text,a.__key);};function e(a,b){return _d$TextNode.call(this,a,b)||this;}var _proto=e.prototype;_proto.createDOM=function createDOM(a){var b=_d$TextNode.prototype.createDOM.call(this,a);require("LexicalUtils").addClassNamesToElement(b,a.theme.hashtag);return b;};e.importJSON=function importJSON(a){var b=f(a.text);b.setFormat(a.format);b.setDetail(a.detail);b.setMode(a.mode);b.setStyle(a.style);return b;};_proto.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_d$TextNode.prototype.exportJSON.call(this),{type:"hashtag"});};_proto.canInsertTextBefore=function canInsertTextBefore(){return!1;};_proto.isTextEntity=function isTextEntity(){return!0;};return e;}(require("Lexical").TextNode);
function f(a){if(a===void 0){a="";}return require("Lexical").$applyNodeReplacement(new e(a));}exports.$createHashtagNode=f;exports.$isHashtagNode=function(a){return a instanceof e;};exports.HashtagNode=e;}),null);
__d("LexicalHistory",["cr:2904"],(function(a,b,c,d,e,f){e.exports=b("cr:2904")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalHistory.prod",["Lexical","LexicalUtils"],(function $module_LexicalHistory_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";
function y(b,a,l,h,n){if(null===b||0===l.size&&0===h.size&&!n)return 0;var f=a._selection,d=b._selection;if(n)return 1;if(!(require("Lexical").$isRangeSelection(f)&&require("Lexical").$isRangeSelection(d)&&d.isCollapsed()&&f.isCollapsed()))return 0;n=a._nodeMap;var e=[];for(var _iterator=l,_isArray=Array.isArray(_iterator),_i=0,_iterator=_isArray?_iterator:_iterator[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref;if(_isArray){if(_i>=_iterator.length)break;_ref=_iterator[_i++];}else{_i=_iterator.next();if(_i.done)break;_ref=_i.value;}var m=_ref;l=n.get(m),void 0!==l&&e.push(l);}for(var _iterator2=h,_isArray2=Array.isArray(_iterator2),_i2=0,_iterator2=_isArray2?_iterator2:_iterator2[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref3;if(_isArray2){if(_i2>=_iterator2.length)break;_ref3=_iterator2[_i2++];}else{_i2=_iterator2.next();if(_i2.done)break;_ref3=_i2.value;}var _ref4=_ref3;var _m=_ref4[0];var p=_ref4[1];p&&(h=n.get(_m),void 0===h||require("Lexical").$isRootNode(h)||e.push(h));}if(0===e.length)return 0;if(1<e.length)return h=a._nodeMap,a=h.get(f.anchor.key),d=h.get(d.anchor.key),a&&d&&!b._nodeMap.has(a.__key)&&require("Lexical").$isTextNode(a)&&
1===a.__text.length&&1===f.anchor.offset?2:0;a=e[0];b=b._nodeMap.get(a.__key);if(!require("Lexical").$isTextNode(b)||!require("Lexical").$isTextNode(a)||b.__mode!==a.__mode)return 0;b=b.__text;a=a.__text;if(b===a)return 0;f=f.anchor;d=d.anchor;if(f.key!==d.key||"text"!==f.type)return 0;f=f.offset;d=d.offset;b=a.length-b.length;return 1===b&&d===f-1?2:-1===b&&d===f+1?3:-1===b&&d===f?4:0;}
function z(b,a){var l=Date.now(),h=0;return function(n,f,d,e,m,p){var r=Date.now();if(p.has("historic"))return h=0,l=r,2;var q=y(n,f,e,m,b.isComposing()),v=function(){var k=null===d||d.editor===b,g=p.has("history-push");if(!g&&k&&p.has("history-merge"))return 0;if(null===n)return 1;var t=f._selection;if(!(0<e.size||0<m.size))return null!==t?0:2;if(!1===g&&0!==q&&q===h&&r<l+a&&k)return 0;if(1===e.size){{g=Array.from(e)[0];k=n._nodeMap.get(g);g=f._nodeMap.get(g);t=n._selection;var u=f._selection,w=!1;require("Lexical").$isRangeSelection(t)&&
require("Lexical").$isRangeSelection(u)&&(w="element"===t.anchor.type&&"element"===t.focus.type&&"text"===u.anchor.type&&"text"===u.focus.type);k=!w&&require("Lexical").$isTextNode(k)&&require("Lexical").$isTextNode(g)?k.__type===g.__type&&k.__text===g.__text&&k.__mode===g.__mode&&k.__detail===g.__detail&&k.__style===g.__style&&k.__format===g.__format&&k.__parent===g.__parent:!1;}if(k)return 0;}return 1;}();l=r;h=q;return v;};}exports.createEmptyHistoryState=function(){return{current:null,redoStack:[],undoStack:[]};};
exports.registerHistory=function(b,a,l){var Lexical;var h=z(b,l);l=function l(_ref5){var d=_ref5.editorState,e=_ref5.prevEditorState,m=_ref5.dirtyLeaves,p=_ref5.dirtyElements,r=_ref5.tags;var q=a.current,v=a.redoStack,k=a.undoStack,g=null===q?null:q.editorState;if(null===q||d!==g){e=h(e,d,q,m,p,r);if(1===e)0!==v.length&&(a.redoStack=[],b.dispatchCommand(require("Lexical").CAN_REDO_COMMAND,!1)),null!==q&&(k.push(babelHelpers["extends"]({},q)),b.dispatchCommand(require("Lexical").CAN_UNDO_COMMAND,!0));else if(2===e)return;a.current={editor:b,editorState:d};}};var n=require("LexicalUtils").mergeRegister(b.registerCommand((Lexical=require("Lexical")).UNDO_COMMAND,
function(){var d=a.redoStack,e=a.undoStack;if(0!==e.length){var m=a.current,p=e.pop();null!==m&&(d.push(m),b.dispatchCommand(require("Lexical").CAN_REDO_COMMAND,!0));0===e.length&&b.dispatchCommand(require("Lexical").CAN_UNDO_COMMAND,!1);a.current=p||null;p&&p.editor.setEditorState(p.editorState,{tag:"historic"});}return!0;},Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(Lexical.REDO_COMMAND,function(){var d=a.redoStack;var e=a.undoStack;if(0!==d.length){var m=a.current;null!==m&&(e.push(m),b.dispatchCommand(require("Lexical").CAN_UNDO_COMMAND,!0));e=d.pop();0===d.length&&
b.dispatchCommand(require("Lexical").CAN_REDO_COMMAND,!1);a.current=e||null;e&&e.editor.setEditorState(e.editorState,{tag:"historic"});}return!0;},Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(Lexical.CLEAR_EDITOR_COMMAND,function(){a.undoStack=[];a.redoStack=[];a.current=null;return!1;},Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(Lexical.CLEAR_HISTORY_COMMAND,function(){a.undoStack=[];a.redoStack=[];a.current=null;b.dispatchCommand(require("Lexical").CAN_REDO_COMMAND,!1);b.dispatchCommand(require("Lexical").CAN_UNDO_COMMAND,!1);return!0;},Lexical.COMMAND_PRIORITY_EDITOR),b.registerUpdateListener(l)),
f=b.registerUpdateListener(l);return function(){n();f();};};}),null);
__d("LexicalHistoryPlugin",["cr:293"],(function(a,b,c,d,e,f){e.exports=b("cr:293")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalHistoryPlugin.prod",["LexicalComposerContext","LexicalHistory","react"],(function $module_LexicalHistoryPlugin_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var c_react;var g=c_react||(c_react=require("react"));function h(a,b,e){if(e===void 0){e=1000;}var f=g.useMemo(function(){return b||require("LexicalHistory").createEmptyHistoryState();},[b]);g.useEffect(function(){return require("LexicalHistory").registerHistory(a,f,e);},[e,a,f]);}exports.createEmptyHistoryState=require("LexicalHistory").createEmptyHistoryState;exports.HistoryPlugin=function(_ref){var a=_ref.externalHistoryState;var _c$useLexicalComposer=require("LexicalComposerContext").useLexicalComposerContext(),b=_c$useLexicalComposer[0];h(b,a);return null;};}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalHtml.prod",["Lexical","LexicalSelection"],(function $module_LexicalHtml_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";
function r(c,d,h,a){if(a===void 0){a=null;}var e=null!=a?d.isSelected(a):!0,k=require("Lexical").$isElementNode(d)&&d.excludeFromCopy("html");var f=d;null!==a&&(f=require("LexicalSelection").$cloneWithProperties(d),f=require("Lexical").$isTextNode(f)&&null!=a?require("LexicalSelection").$sliceSelectedTextNodeContent(a,f):f);var g=require("Lexical").$isElementNode(f)?f.getChildren():[],_f$exportDOM=f.exportDOM(c),b=_f$exportDOM.element,l=_f$exportDOM.after;if(!b)return!1;var n=document.createDocumentFragment();for(var p=0;p<g.length;p++){var t=g[p],w=r(c,t,n,a);!e&&require("Lexical").$isElementNode(d)&&w&&d.extractWithChild(t,a,"html")&&(e=!0);}e&&!k?(b.append(n),h.append(b),
l&&(c=l.call(f,b))&&b.replaceWith(c)):h.append(n);return e;}var u=new Set(["STYLE","SCRIPT"]);
function v(c,d,h,a){var _k;if(h===void 0){h=new Map();}var e=[];if(u.has(c.nodeName))return e;var k=null;var f,_c=c,g=_c.nodeName,b=d._htmlConversions.get(g.toLowerCase());g=null;if(void 0!==b){for(var _iterator=b,_isArray=Array.isArray(_iterator),_i=0,_iterator=_isArray?_iterator:_iterator[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){if(_isArray){if(_i>=_iterator.length)break;f=_iterator[_i++];}else{_i=_iterator.next();if(_i.done)break;f=_i.value;}b=f(c),null!==b&&(null===g||g.priority<b.priority)&&(g=b);}}g=(f=null!==g?g.conversion:null)?f(c):null;f=null;if(null!==g){f=g.after;b=g.node;k=Array.isArray(b)?b[b.length-1]:b;if(null!==k){var _e;for(var _iterator2=h,_isArray2=Array.isArray(_iterator2),_i2=0,_iterator2=_isArray2?_iterator2:_iterator2[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref2;if(_isArray2){if(_i2>=_iterator2.length)break;_ref2=_iterator2[_i2++];}else{_i2=_iterator2.next();if(_i2.done)break;_ref2=_i2.value;}var _ref=_ref2;var l=_ref[1];if(k=l(k,a),!k)break;}k&&(_e=e).push.apply(_e,Array.isArray(b)?b:[k]);}null!=g.forChild&&h.set(c.nodeName,g.forChild);}c=c.childNodes;a=
[];for(l=0;l<c.length;l++){var _a;(_a=a).push.apply(_a,v(c[l],d,new Map(h),k));}null!=f&&(a=f(a));null==k?e=e.concat(a):require("Lexical").$isElementNode(k)&&(_k=k).append.apply(_k,a);return e;}
exports.$generateHtmlFromNodes=function(c,d){if("undefined"===typeof document||"undefined"===typeof window)throw Error("To use $generateHtmlFromNodes in headless mode please initialize a headless browser implementation such as JSDom before calling this function.");var h=document.createElement("div"),a=require("Lexical").$getRoot().getChildren();for(var e=0;e<a.length;e++){r(c,a[e],h,d);}return h.innerHTML;};
exports.$generateNodesFromDOM=function(c,d){d=d.body?d.body.childNodes:[];var h=[];for(var e=0;e<d.length;e++){var a=d[e];u.has(a.nodeName)||(a=v(a,c),null!==a&&(h=h.concat(a)));}return h;};}),null);
__d("LexicalLink",["cr:2905"],(function(a,b,c,d,e,f){e.exports=b("cr:2905")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalLink.prod",["Lexical","LexicalUtils"],(function $module_LexicalLink_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var p=new Set(["http:","https:","mailto:","sms:","tel:"]);var
q=function(_n$ElementNode){babelHelpers.inheritsLoose(q,_n$ElementNode);q.getType=function getType(){return"link";};q.clone=function clone(a){return new q(a.__url,{rel:a.__rel,target:a.__target,title:a.__title},a.__key);};function q(a,b,d){var _this;if(b===void 0){b={};}_this=_n$ElementNode.call(this,d)||this;var _b=b,_b$target=_b.target,l=_b$target===void 0?null:_b$target,_b$rel=_b.rel,h=_b$rel===void 0?null:_b$rel,_b$title=_b.title,e=_b$title===void 0?null:_b$title;_this.__url=a;_this.__target=l;_this.__rel=h;_this.__title=e;return _this;}var _proto=q.prototype;_proto.createDOM=function createDOM(a){var b=document.createElement("a");b.href=this.sanitizeUrl(this.__url);null!==this.__target&&(b.target=this.__target);null!==this.__rel&&(b.rel=this.__rel);null!==this.__title&&(b.title=this.__title);require("LexicalUtils").addClassNamesToElement(b,
a.theme.link);return b;};_proto.updateDOM=function updateDOM(a,b){var d=this.__url,l=this.__target,h=this.__rel,e=this.__title;d!==a.__url&&(b.href=d);l!==a.__target&&(l?b.target=l:b.removeAttribute("target"));h!==a.__rel&&(h?b.rel=h:b.removeAttribute("rel"));e!==a.__title&&(e?b.title=e:b.removeAttribute("title"));return!1;};q.importDOM=function importDOM(){return{a:function a(){return{conversion:r,priority:1};}};};q.importJSON=function importJSON(a){var b=t(a.url,{rel:a.rel,target:a.target,title:a.title});b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);
return b;};_proto.sanitizeUrl=function sanitizeUrl(a){try{var b=new URL(a);if(!p.has(b.protocol))return"about:blank";}catch(_unused){}return a;};_proto.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_n$ElementNode.prototype.exportJSON.call(this),{rel:this.getRel(),target:this.getTarget(),title:this.getTitle(),type:"link",url:this.getURL(),version:1});};_proto.getURL=function getURL(){return this.getLatest().__url;};_proto.setURL=function setURL(a){this.getWritable().__url=a;};_proto.getTarget=function getTarget(){return this.getLatest().__target;};_proto.setTarget=function setTarget(a){this.getWritable().__target=a;};_proto.getRel=function getRel(){return this.getLatest().__rel;};_proto.setRel=function setRel(a){this.getWritable().__rel=a;};_proto.getTitle=function getTitle(){return this.getLatest().__title;};_proto.setTitle=function setTitle(a){this.getWritable().__title=
a;};_proto.insertNewAfter=function insertNewAfter(a,b){if(b===void 0){b=!0;}a=this.getParentOrThrow().insertNewAfter(a,b);return require("Lexical").$isElementNode(a)?(b=t(this.__url,{rel:this.__rel,target:this.__target,title:this.__title}),a.append(b),b):null;};_proto.canInsertTextBefore=function canInsertTextBefore(){return!1;};_proto.canInsertTextAfter=function canInsertTextAfter(){return!1;};_proto.canBeEmpty=function canBeEmpty(){return!1;};_proto.isInline=function isInline(){return!0;};_proto.extractWithChild=function extractWithChild(a,b){if(!require("Lexical").$isRangeSelection(b))return!1;a=b.anchor.getNode();var d=b.focus.getNode();return this.isParentOf(a)&&this.isParentOf(d)&&0<b.getTextContent().length;};return q;}(require("Lexical").ElementNode);
function r(a){var b=null;if(require("LexicalUtils").isHTMLAnchorElement(a)){var d=a.textContent;null!==d&&""!==d&&(b=t(a.getAttribute("href")||"",{rel:a.getAttribute("rel"),target:a.getAttribute("target"),title:a.getAttribute("title")}));}return{node:b};}function t(a,b){return require("Lexical").$applyNodeReplacement(new q(a,b));}function v(a){return a instanceof q;}var
w=function(_q){babelHelpers.inheritsLoose(w,_q);function w(){return _q.apply(this,arguments)||this;}w.getType=function getType(){return"autolink";};w.clone=function clone(a){return new w(a.__url,{rel:a.__rel,target:a.__target,title:a.__title},a.__key);};w.importJSON=function importJSON(a){var b=x(a.url,{rel:a.rel,target:a.target,title:a.title});b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);return b;};w.importDOM=function importDOM(){return null;};var _proto2=w.prototype;_proto2.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_q.prototype.exportJSON.call(this),{type:"autolink",version:1});};_proto2.insertNewAfter=function insertNewAfter(a,b){if(b===void 0){b=!0;}a=this.getParentOrThrow().insertNewAfter(a,b);return require("Lexical").$isElementNode(a)?(
b=x(this.__url,{rel:this._rel,target:this.__target,title:this.__title}),a.append(b),b):null;};return w;}(q);function x(a,b){return require("Lexical").$applyNodeReplacement(new w(a,b));}var y=require("Lexical").createCommand("TOGGLE_LINK_COMMAND");function z(a,b){for(;null!==a&&null!==(a=a.getParent())&&!b(a);){;}return a;}exports.$createAutoLinkNode=x;exports.$createLinkNode=t;exports.$isAutoLinkNode=function(a){return a instanceof w;};exports.$isLinkNode=v;exports.AutoLinkNode=w;exports.LinkNode=q;exports.TOGGLE_LINK_COMMAND=y;
exports.toggleLink=function(a,b){if(b===void 0){b={};}var _b2=b,d=_b2.target,l=_b2.title,h=void 0===b.rel?"noreferrer":b.rel;b=require("Lexical").$getSelection();if(require("Lexical").$isRangeSelection(b))if(b=b.extract(),null===a)b.forEach(function(m){m=m.getParent();if(v(m)){var c=m.getChildren();for(var f=0;f<c.length;f++){m.insertBefore(c[f]);}m.remove();}});else{if(1===b.length){var e=b[0];e=v(e)?e:z(e,v);if(null!==e){e.setURL(a);void 0!==d&&e.setTarget(d);null!==h&&e.setRel(h);void 0!==l&&e.setTitle(l);return;}}var m=null,c=null;b.forEach(function(f){var g=f.getParent();
if(g!==c&&null!==g&&(!require("Lexical").$isElementNode(f)||f.isInline()))if(v(g))c=g,g.setURL(a),void 0!==d&&g.setTarget(d),null!==h&&c.setRel(h),void 0!==l&&c.setTitle(l);else if(g.is(m)||(m=g,c=t(a,{rel:h,target:d}),v(g)?null===f.getPreviousSibling()?g.insertBefore(c):g.insertAfter(c):f.insertBefore(c)),v(f)){if(!f.is(c)){if(null!==c){g=f.getChildren();for(var u=0;u<g.length;u++){c.append(g[u]);}}f.remove();}}else null!==c&&c.append(f);});}};}),null);
__d("LexicalOverflow",["cr:2908"],(function(a,b,c,d,e,f){e.exports=b("cr:2908")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalOverflow.prod",["Lexical"],(function $module_LexicalOverflow_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var
d=function(_b$ElementNode){babelHelpers.inheritsLoose(d,_b$ElementNode);d.getType=function getType(){return"overflow";};d.clone=function clone(a){return new d(a.__key);};d.importJSON=function importJSON(){return e();};d.importDOM=function importDOM(){return null;};function d(a){var _this;_this=_b$ElementNode.call(this,a)||this;_this.__type="overflow";return _this;}var _proto=d.prototype;_proto.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_b$ElementNode.prototype.exportJSON.call(this),{type:"overflow"});};_proto.createDOM=function createDOM(a){var c=document.createElement("span");a=a.theme.characterLimit;"string"===typeof a&&(c.className=a);return c;};_proto.updateDOM=function updateDOM(){return!1;};_proto.insertNewAfter=function insertNewAfter(a,c){if(c===void 0){c=!0;}return this.getParentOrThrow().insertNewAfter(a,c);};_proto.excludeFromCopy=function excludeFromCopy(){return!0;};return d;}(require("Lexical").ElementNode);
function e(){return require("Lexical").$applyNodeReplacement(new d());}exports.$createOverflowNode=e;exports.$isOverflowNode=function(a){return a instanceof d;};exports.OverflowNode=d;}),null);
__d("LexicalPlainText",["cr:2909"],(function(a,b,c,d,e,f){e.exports=b("cr:2909")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalPlainText.prod",["Lexical","LexicalClipboard","LexicalSelection","LexicalUtils"],(function $module_LexicalPlainText_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var k="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,m=k&&"documentMode"in document?document.documentMode:null;k&&/Mac|iPod|iPhone|iPad/.test(navigator.platform);k&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent);
var n=k&&"InputEvent"in window&&!m?"getTargetRanges"in new window.InputEvent("input"):!1,p=k&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),q=k&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,r=k&&/^(?=.*Chrome).*/i.test(navigator.userAgent),t=k&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!r;
function u(d,b){b.update(function(){if(null!==d){var c=d instanceof KeyboardEvent?null:d.clipboardData,e=require("Lexical").$getSelection();if(null!==e&&null!=c){d.preventDefault();var l=require("LexicalClipboard").$getHtmlContent(b);null!==l&&c.setData("text/html",l);c.setData("text/plain",e.getTextContent());}}});}function v(d,b){d.preventDefault();b.update(function(){var c=require("Lexical").$getSelection(),e=d.clipboardData;null!=e&&require("Lexical").$isRangeSelection(c)&&require("LexicalClipboard").$insertDataTransferForPlainText(e,c);},{tag:"paste"});}
function w(d,b){u(d,b);b.update(function(){var c=require("Lexical").$getSelection();require("Lexical").$isRangeSelection(c)&&c.removeText();});}
exports.registerPlainText=function(d){var Lexical;return require("LexicalUtils").mergeRegister(d.registerCommand((Lexical=require("Lexical")).DELETE_CHARACTER_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;c.deleteCharacter(b);return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.DELETE_WORD_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;c.deleteWord(b);return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.DELETE_LINE_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;c.deleteLine(b);
return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.CONTROLLED_TEXT_INSERTION_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;if("string"===typeof b)c.insertText(b);else{var e=b.dataTransfer;null!=e?require("LexicalClipboard").$insertDataTransferForPlainText(e,c):(b=b.data)&&c.insertText(b);}return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.REMOVE_TEXT_COMMAND,function(){var b=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(b))return!1;b.removeText();return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.INSERT_LINE_BREAK_COMMAND,
function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;c.insertLineBreak(b);return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.INSERT_PARAGRAPH_COMMAND,function(){var b=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(b))return!1;b.insertLineBreak();return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.KEY_ARROW_LEFT_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;var e=b.shiftKey;return require("LexicalSelection").$shouldOverrideDefaultCharacterSelection(c,!0)?(b.preventDefault(),require("LexicalSelection").$moveCharacter(c,
e,!0),!0):!1;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.KEY_ARROW_RIGHT_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;var e=b.shiftKey;return require("LexicalSelection").$shouldOverrideDefaultCharacterSelection(c,!1)?(b.preventDefault(),require("LexicalSelection").$moveCharacter(c,e,!1),!0):!1;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.KEY_BACKSPACE_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;b.preventDefault();return d.dispatchCommand(require("Lexical").DELETE_CHARACTER_COMMAND,!0);},Lexical.COMMAND_PRIORITY_EDITOR),
d.registerCommand(Lexical.KEY_DELETE_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;b.preventDefault();return d.dispatchCommand(require("Lexical").DELETE_CHARACTER_COMMAND,!1);},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.KEY_ENTER_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;if(null!==b){if((q||p||t)&&n)return!1;b.preventDefault();}return d.dispatchCommand(require("Lexical").INSERT_LINE_BREAK_COMMAND,!1);},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.COPY_COMMAND,function(b){var c=require("Lexical").$getSelection();
if(!require("Lexical").$isRangeSelection(c))return!1;u(b,d);return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.CUT_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;w(b,d);return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.PASTE_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;v(b,d);return!0;},Lexical.COMMAND_PRIORITY_EDITOR),d.registerCommand(Lexical.DROP_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;b.preventDefault();return!0;},Lexical.COMMAND_PRIORITY_EDITOR),
d.registerCommand(Lexical.DRAGSTART_COMMAND,function(b){var c=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(c))return!1;b.preventDefault();return!0;},Lexical.COMMAND_PRIORITY_EDITOR));};}),null);
__d("LexicalPlainTextPlugin",["cr:739"],(function(a,b,c,d,e,f){e.exports=b("cr:739")}),null);
__d("useLexicalEditable",["cr:4793"],(function(a,b,c,d,e,f){e.exports=b("cr:4793")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalPlainTextPlugin.prod",["LexicalComposerContext","LexicalDragon","LexicalPlainText","LexicalText","LexicalUtils","ReactDOMComet","react","useLexicalEditable"],(function $module_LexicalPlainTextPlugin_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var c_react;var l=c_react||(c_react=require("react")),v="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement?l.useLayoutEffect:l.useEffect;function w(a){return a.getEditorState().read(require("LexicalText").$canShowPlaceholderCurry(a.isComposing()));}
function x(a){var _l$useState=l.useState(function(){return w(a);}),d=_l$useState[0],c=_l$useState[1];v(function(){function e(){var f=w(a);c(f);}e();return require("LexicalUtils").mergeRegister(a.registerUpdateListener(function(){e();}),a.registerEditableListener(function(){e();}));},[a]);return d;}
function y(a,d){var _l$useState2=l.useState(function(){return a.getDecorators();}),c=_l$useState2[0],e=_l$useState2[1];v(function(){return a.registerDecoratorListener(function(f){require("ReactDOMComet").flushSync(function(){e(f);});});},[a]);l.useEffect(function(){e(a.getDecorators());},[a]);return l.useMemo(function(){var f=[],q=Object.keys(c);for(var h=0;h<q.length;h++){var k=q[h],A=l.createElement(d,{onError:function onError(z){return a._onError(z);}},l.createElement(l.Suspense,{fallback:null},c[k])),r=a.getElementByKey(k);null!==r&&f.push(require("ReactDOMComet").createPortal(A,r,k));}return f;},[d,c,a]);}
function B(a){v(function(){return require("LexicalUtils").mergeRegister(require("LexicalPlainText").registerPlainText(a),require("LexicalDragon").registerDragonSupport(a));},[a]);}function C(_ref){var a=_ref.content;var _b$useLexicalComposer=require("LexicalComposerContext").useLexicalComposerContext(),d=_b$useLexicalComposer[0];d=x(d);var c=require("useLexicalEditable")();return d?"function"===typeof a?a(c):a:null;}exports.PlainTextPlugin=function(_ref2){var a=_ref2.contentEditable,d=_ref2.placeholder,c=_ref2.ErrorBoundary;var _b$useLexicalComposer2=require("LexicalComposerContext").useLexicalComposerContext(),e=_b$useLexicalComposer2[0];c=y(e,c);B(e);return l.createElement(l.Fragment,null,a,l.createElement(C,{content:d}),c);};}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalSelection.prod",["Lexical"],(function $module_LexicalSelection_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var u=new Map();function v(a){for(;null!=a;){if(a.nodeType===Node.TEXT_NODE)return a;a=a.firstChild;}return null;}function w(a){var b=a.parentNode;if(null==b)throw Error("Should never happen");return[b,Array.from(b.childNodes).indexOf(a)];}function y(a){var b={};a=a.split(";");for(var _iterator=a,_isArray=Array.isArray(_iterator),_i=0,_iterator=_isArray?_iterator:_iterator[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref;if(_isArray){if(_i>=_iterator.length)break;_ref=_iterator[_i++];}else{_i=_iterator.next();if(_i.done)break;_ref=_i.value;}var c=_ref;if(""!==c){var _c$split=c.split(/:([^]+)/),e=_c$split[0],d=_c$split[1];b[e.trim()]=d.trim();}}return b;}function z(a){var b=u.get(a);void 0===b&&(b=y(a),u.set(a,b));return b;}
function A(a){var b="";for(var c in a){c&&(b+=c+": "+a[c]+";");}return b;}function B(a,b){var c=z("getStyle"in a?a.getStyle():a.style);b=Object.entries(b).reduce(function(e,_ref2){var d=_ref2[0],f=_ref2[1];null===f?delete e[d]:e[d]=f;return e;},babelHelpers["extends"]({},c));c=A(b);a.setStyle(c);u.set(c,b);}function C(a){for(;null!==a&&!require("Lexical").$isRootOrShadowRoot(a);){var b=a.getLatest(),c=a.getParent();0===b.getChildrenSize()&&a.remove(!0);a=c;}}
function D(a,b,c,e,d){if(d===void 0){d=null;}if(0!==b.length){var f=b[0],h=new Map(),g=[];f=require("Lexical").$isElementNode(f)?f:f.getParentOrThrow();f.isInline()&&(f=f.getParentOrThrow());for(var l=!1;null!==f;){var m=f.getPreviousSibling();if(null!==m){f=m;l=!0;break;}f=f.getParentOrThrow();if(require("Lexical").$isRootOrShadowRoot(f))break;}m=new Set();for(var q=0;q<c;q++){var p=b[q];require("Lexical").$isElementNode(p)&&0===p.getChildrenSize()&&m.add(p.getKey());}var n=new Set();for(q=0;q<c;q++){p=b[q];var r=p.getParent();null!==r&&r.isInline()&&(r=r.getParent());if(null!==
r&&require("Lexical").$isLeafNode(p)&&!n.has(p.getKey())){if(p=r.getKey(),void 0===h.get(p)){(function(){var t=e();t.setFormat(r.getFormatType());t.setIndent(r.getIndent());g.push(t);h.set(p,t);r.getChildren().forEach(function(x){t.append(x);n.add(x.getKey());require("Lexical").$isElementNode(x)&&x.getChildrenKeys().forEach(function(G){return n.add(G);});});C(r);})();}}else m.has(p.getKey())&&(r=e(),r.setFormat(p.getFormatType()),r.setIndent(p.getIndent()),g.push(r),p.remove(!0));}if(null!==d)for(b=0;b<g.length;b++){d.append(g[b]);}b=null;if(require("Lexical").$isRootOrShadowRoot(f)){if(l){if(null!==
d)f.insertAfter(d);else for(d=g.length-1;0<=d;d--){f.insertAfter(g[d]);}}else if(l=f.getFirstChild(),require("Lexical").$isElementNode(l)&&(f=l),null===l){if(d)f.append(d);else for(d=0;d<g.length;d++){l=g[d],f.append(l),b=l;}}else if(null!==d)l.insertBefore(d);else for(f=0;f<g.length;f++){d=g[f],l.insertBefore(d),b=d;}}else if(d)f.insertAfter(d);else for(d=g.length-1;0<=d;d--){l=g[d],f.insertAfter(l),b=l;}g=require("Lexical").$getPreviousSelection();require("Lexical").$isRangeSelection(g)&&g.anchor.getNode().isAttached()&&g.focus.getNode().isAttached()?require("Lexical").$setSelection(g.clone()):
null!==b?b.selectEnd():a.dirty=!0;}}function E(a,b,c,e){a.modify(b?"extend":"move",c,e);}function F(a){a=a.anchor.getNode();return"rtl"===(require("Lexical").$isRootNode(a)?a:a.getParentOrThrow()).getDirection();}exports.$addNodeStyle=function(a){a=a.getStyle();var b=y(a);u.set(a,b);};
exports.$cloneWithProperties=function(a){a=a.getLatest();var b=a.constructor.clone(a);b.__parent=a.__parent;b.__next=a.__next;b.__prev=a.__prev;if(require("Lexical").$isElementNode(a)&&require("Lexical").$isElementNode(b))return b.__first=a.__first,b.__last=a.__last,b.__size=a.__size,b.__format=a.__format,b.__indent=a.__indent,b.__dir=a.__dir,b;require("Lexical").$isTextNode(a)&&require("Lexical").$isTextNode(b)&&(b.__format=a.__format,b.__style=a.__style,b.__mode=a.__mode,b.__detail=a.__detail);return b;};
exports.$getSelectionStyleValueForProperty=function(a,b,c){if(c===void 0){c="";}var e=null,d=a.getNodes();var f=a.anchor,h=a.focus,g=a.isBackward();var l=g?h.offset:f.offset;f=g?h.getNode():f.getNode();if(""!==a.style&&(a=z(a.style),null!==a&&b in a))return a[b];for(a=0;a<d.length;a++){var m=d[a];if((0===a||0!==l||!m.is(f))&&require("Lexical").$isTextNode(m))if(h=b,g=c,m=m.getStyle(),m=z(m),h=null!==m?m[h]||g:g,null===e)e=h;else if(e!==h){e="";break;}}return null===e?c:e;};
exports.$isAtNodeEnd=function(a){return"text"===a.type?a.offset===a.getNode().getTextContentSize():a.offset===a.getNode().getChildrenSize();};exports.$isParentElementRTL=F;exports.$moveCaretSelection=E;exports.$moveCharacter=function(a,b,c){var e=F(a);E(a,b,c?!e:e,"character");};
exports.$patchStyleText=function(a,b){var c=a.getNodes();var e=c.length-1,d=c[0],f=c[e];if(a.isCollapsed())B(a,b);else{var h=a.anchor,g=a.focus,l=d.getTextContent().length,m=g.offset,q=h.offset,p=h.isBefore(g),n=p?q:m;a=p?m:q;var r=p?h.type:g.type,t=p?g.type:h.type;h=p?g.key:h.key;require("Lexical").$isTextNode(d)&&n===l&&(g=d.getNextSibling(),require("Lexical").$isTextNode(g)&&(n=q=0,d=g));if(1===c.length)require("Lexical").$isTextNode(d)&&(n="element"===r?0:q>m?m:q,a="element"===t?l:q>m?q:m,n!==a&&(0===n&&a===l?(B(d,b),d.select(n,a)):(c=d.splitText(n,
a),c=0===n?c[0]:c[1],B(c,b),c.select(0,a-n))));else for(require("Lexical").$isTextNode(d)&&n<d.getTextContentSize()&&(0!==n&&(d=d.splitText(n)[1]),B(d,b)),require("Lexical").$isTextNode(f)&&(n=f.getTextContent().length,f.__key!==h&&0!==a&&(a=n),a!==n&&(_f$splitText=f.splitText(a),f=_f$splitText[0],_f$splitText),0!==a&&B(f,b)),a=1;a<e;a++){var _f$splitText;n=c[a],l=n.getKey(),require("Lexical").$isTextNode(n)&&l!==d.getKey()&&l!==f.getKey()&&!n.isToken()&&B(n,b);}}};
exports.$selectAll=function(a){var b=a.anchor;a=a.focus;var c=b.getNode().getTopLevelElementOrThrow().getParentOrThrow();var e=c.getFirstDescendant();c=c.getLastDescendant();var d="element",f="element",h=0;require("Lexical").$isTextNode(e)?d="text":require("Lexical").$isElementNode(e)||null===e||(e=e.getParentOrThrow());require("Lexical").$isTextNode(c)?(f="text",h=c.getTextContentSize()):require("Lexical").$isElementNode(c)||null===c||(c=c.getParentOrThrow());e&&c&&(b.set(e.getKey(),0,d),a.set(c.getKey(),h,f));};
exports.$setBlocksType=function(a,b){if("root"===a.anchor.key){b=b();var c=require("Lexical").$getRoot();(a=c.getFirstChild())?a.replace(b,!0):c.append(b);}else for(c=a.getNodes(),a=a.anchor.getNode().getParentOrThrow(),-1===c.indexOf(a)&&c.push(a),a.isInline()&&(a=a.getParentOrThrow(),-1===c.indexOf(a)&&c.push(a)),a=0;a<c.length;a++){var f=c[a];var e=f;if(!require("Lexical").$isElementNode(e)||require("Lexical").$isRootOrShadowRoot(e))e=!1;else{var d=e.getFirstChild();d=null===d||require("Lexical").$isLineBreakNode(d)||require("Lexical").$isTextNode(d)||d.isInline();e=!e.isInline()&&
!1!==e.canBeEmpty()&&d;}e&&(e=b(),e.setFormat(f.getFormatType()),e.setIndent(f.getIndent()),f.replace(e,!0));}};exports.$shouldOverrideDefaultCharacterSelection=function(a,b){a=require("Lexical").$getAdjacentNode(a.focus,b);return require("Lexical").$isDecoratorNode(a)&&!a.isIsolated()||require("Lexical").$isElementNode(a)&&!a.isInline()&&!a.canBeEmpty();};
exports.$sliceSelectedTextNodeContent=function(a,b){if(b.isSelected()&&!b.isSegmented()&&!b.isToken()&&(require("Lexical").$isRangeSelection(a)||require("Lexical").DEPRECATED_$isGridSelection(a))){var c=a.anchor.getNode(),e=a.focus.getNode(),d=b.is(c),f=b.is(e);if(d||f){d=a.isBackward();var _a$getCharacterOffset=a.getCharacterOffsets(),h=_a$getCharacterOffset[0],g=_a$getCharacterOffset[1];a=c.is(e);f=b.is(d?e:c);e=b.is(d?c:e);c=0;var l=void 0;a?(c=h>g?g:h,l=h>g?h:g):f?(c=d?g:h,l=void 0):e&&(d=d?h:g,c=0,l=d);b.__text=b.__text.slice(c,l);}}return b;};
exports.$wrapNodes=function(a,b,c){if(c===void 0){c=null;}var e=a.getNodes();var d=e.length;var f=a.anchor;if(0===d||1===d&&"element"===f.type&&0===f.getNode().getChildrenSize()){a="text"===f.type?f.getNode().getParentOrThrow():f.getNode();e=a.getChildren();var g=b();g.setFormat(a.getFormatType());g.setIndent(a.getIndent());e.forEach(function(l){return g.append(l);});c&&(g=c.append(g));a.replace(g);}else{f=null;var h=[];for(var _g=0;_g<d;_g++){var l=e[_g];require("Lexical").$isRootOrShadowRoot(l)?(D(a,h,h.length,b,c),h=[],f=l):null===f||null!==f&&require("Lexical").$hasAncestor(l,
f)?h.push(l):(D(a,h,h.length,b,c),h=[l]);}D(a,h,h.length,b,c);}};
exports.createDOMRange=function(a,b,c,e,d){var _w,_w2;var f=b.getKey(),h=e.getKey(),g=document.createRange(),l=a.getElementByKey(f);a=a.getElementByKey(h);require("Lexical").$isTextNode(b)&&(l=v(l));require("Lexical").$isTextNode(e)&&(a=v(a));if(void 0===b||void 0===e||null===l||null===a)return null;"BR"===l.nodeName&&(_w=w(l),l=_w[0],c=_w[1],_w);"BR"===a.nodeName&&(_w2=w(a),a=_w2[0],d=_w2[1],_w2);b=l.firstChild;l===a&&null!=b&&"BR"===b.nodeName&&0===c&&0===d&&(d=1);try{g.setStart(l,c),g.setEnd(a,d);}catch(m){return null;}!g.collapsed||c===d&&f===h||(g.setStart(a,d),g.setEnd(l,
c));return g;};exports.createRectsFromDOMRange=function(a,b){var c=a.getRootElement();if(null===c)return[];a=c.getBoundingClientRect();c=getComputedStyle(c);c=parseFloat(c.paddingLeft)+parseFloat(c.paddingRight);b=Array.from(b.getClientRects());var e=b.length;b.sort(function(f,h){var g=f.top-h.top;return 3>=Math.abs(g)?f.left-h.left:g;});var d;for(var f=0;f<e;f++){var h=b[f],g=h.width+c===a.width;d&&d.top<=h.top&&d.top+d.height>h.top&&d.left+d.width>h.left||g?(b.splice(f--,1),e--):d=h;}return b;};
exports.getStyleObjectFromCSS=z;
exports.trimTextContentFromAnchor=function(a,b,c){var e=b.getNode();if(require("Lexical").$isElementNode(e)){var d=e.getDescendantByIndex(b.offset);null!==d&&(e=d);}for(;0<c&&null!==e;){var f=e.getPreviousSibling(),h=0;if(null===f){d=e.getParentOrThrow();for(var g=d.getPreviousSibling();null===g;){d=d.getParent();if(null===d){f=null;break;}g=d.getPreviousSibling();}null!==d&&(h=d.isInline()?0:2,f=require("Lexical").$isElementNode(g)?g.getLastDescendant():g);}g=e.getTextContent();""===g&&require("Lexical").$isElementNode(e)&&!e.isInline()&&(g="\n\n");
d=e.getTextContentSize();if(!require("Lexical").$isTextNode(e)||c>=d)g=e.getParent(),e.remove(),null==g||0!==g.getChildrenSize()||require("Lexical").$isRootNode(g)||g.remove(),c-=d+h,e=f;else{(function(){var _e$splitText,_e$splitText2;var l=e.getKey();h=a.getEditorState().read(function(){var q=require("Lexical").$getNodeByKey(l);return require("Lexical").$isTextNode(q)&&q.isSimpleText()?q.getTextContent():null;});f=d-c;var m=g.slice(0,f);null!==h&&h!==g?(c=require("Lexical").$getPreviousSelection(),d=e,e.isSimpleText()?e.setTextContent(h):(d=require("Lexical").$createTextNode(h),e.replace(d)),require("Lexical").$isRangeSelection(c)&&c.isCollapsed()&&(c=c.anchor.offset,
d.select(c,c))):e.isSimpleText()?(h=b.key===l,g=b.offset,g<c&&(g=d),c=h?g-c:0,d=h?g:f,h&&0===c?((_e$splitText=e.splitText(c,d),c=_e$splitText[0],_e$splitText),c.remove()):((_e$splitText2=e.splitText(c,d),c=_e$splitText2[1],_e$splitText2),c.remove())):(c=require("Lexical").$createTextNode(m),e.replace(c));c=0;})();}}};}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("LexicalUtils.prod",["Lexical","LexicalSelection","Promise"],(function $module_LexicalUtils_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";function p(a){var b=new URLSearchParams();b.append("code",a);for(var c=1;c<arguments.length;c++){b.append("v",arguments[c]);}throw Error("Minified Lexical error #"+a+"; visit https://lexical.dev/docs/error?"+b+" for the full message or "+"use the non-minified dev environment for full errors and additional helpful warnings.");}function q(a,b){for(var _iterator=b,_isArray=Array.isArray(_iterator),_i=0,_iterator=_isArray?_iterator:_iterator[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref;if(_isArray){if(_i>=_iterator.length)break;_ref=_iterator[_i++];}else{_i=_iterator.next();if(_i.done)break;_ref=_i.value;}var c=_ref;if(a.type.startsWith(c))return!0;}return!1;}
function t(a,b){for(;a!==require("Lexical").$getRoot()&&null!=a;){if(b(a))return a;a=a.getParent();}return null;}function u(a){return 1===a.nodeType;}exports.$splitNode=require("Lexical").$splitNode;
exports.$dfs=function(a,b){var c=[];a=(a||require("Lexical").$getRoot()).getLatest();b=b||(require("Lexical").$isElementNode(a)?a.getLastDescendant():a);for(var f=a,d=0;null!==(f=f.getParent());){d++;}for(f=d;null!==a&&!a.is(b);){if(c.push({depth:f,node:a}),require("Lexical").$isElementNode(a)&&0<a.getChildrenSize())a=a.getFirstChild(),f++;else for(d=null;null===d&&null!==a;){d=a.getNextSibling(),null===d?(a=a.getParent(),f--):a=d;}}null!==a&&a.is(b)&&c.push({depth:f,node:a});return c;};exports.$findMatchingParent=t;
exports.$getNearestBlockElementAncestorOrThrow=function(a){var b=t(a,function(c){return require("Lexical").$isElementNode(c)&&!c.isInline();});require("Lexical").$isElementNode(b)||p(4,a.__key);return b;};exports.$getNearestNodeOfType=function(a,b){for(;null!=a;){if(a instanceof b)return a;a=a.getParent();}return null;};
exports.$insertNodeToNearestRoot=function(a){var b=require("Lexical").$getSelection()||require("Lexical").$getPreviousSelection();if(require("Lexical").$isRangeSelection(b)){var _b=b,c=_b.focus;b=c.getNode();c=c.offset;if(require("Lexical").$isRootOrShadowRoot(b))c=b.getChildAtIndex(c),null==c?b.append(a):c.insertBefore(a),a.selectNext();else{var f,d;require("Lexical").$isTextNode(b)?(f=b.getParentOrThrow(),d=b.getIndexWithinParent(),0<c&&(d+=1,b.splitText(c))):(f=b,d=c);var _n$$splitNode=require("Lexical").$splitNode(f,d);b=_n$$splitNode[1];b.insertBefore(a);b.selectStart();}}else require("Lexical").$isNodeSelection(b)||require("Lexical").DEPRECATED_$isGridSelection(b)?(
b=b.getNodes(),b[b.length-1].getTopLevelElementOrThrow().insertAfter(a)):require("Lexical").$getRoot().append(a),b=require("Lexical").$createParagraphNode(),a.insertAfter(b),b.select();return a.getLatest();};exports.$restoreEditorState=function(a,b){var c=new Map(),f=a._pendingEditorState;for(var _iterator2=b._nodeMap,_isArray2=Array.isArray(_iterator2),_i2=0,_iterator2=_isArray2?_iterator2:_iterator2[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref3;if(_isArray2){if(_i2>=_iterator2.length)break;_ref3=_iterator2[_i2++];}else{_i2=_iterator2.next();if(_i2.done)break;_ref3=_i2.value;}var _ref4=_ref3;var d=_ref4[0];var e=_ref4[1];var h=require("LexicalSelection").$cloneWithProperties(e);require("Lexical").$isTextNode(h)&&(h.__text=e.__text);c.set(d,h);}f&&(f._nodeMap=c);a._dirtyType=2;a=b._selection;require("Lexical").$setSelection(null===a?null:a.clone());};
exports.$wrapNodeInElement=function(a,b){b=b();a.replace(b);b.append(a);return b;};exports.addClassNamesToElement=function(a){for(var _len=arguments.length,b=new Array(_len>1?_len-1:0),_key=1;_key<_len;_key++){b[_key-1]=arguments[_key];}b.forEach(function(c){var _a$classList;"string"===typeof c&&(c=c.split(" ").filter(function(f){return""!==f;}),(_a$classList=a.classList).add.apply(_a$classList,c));});};exports.isHTMLAnchorElement=function(a){return u(a)&&"A"===a.tagName;};exports.isHTMLElement=u;exports.isMimeType=q;
exports.mediaFileReader=function(a,b){var c=a[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();return new(require("Promise"))(function(f,d){var e=[],h=function h(){var _c$next=c.next(),m=_c$next.done,k=_c$next.value;if(m)return f(e);var l=new FileReader();l.addEventListener("error",d);l.addEventListener("load",function(){var r=l.result;"string"===typeof r&&e.push({file:k,result:r});h();});q(k,b)?l.readAsDataURL(k):h();};h();});};exports.mergeRegister=function(){for(var _len2=arguments.length,a=new Array(_len2),_key2=0;_key2<_len2;_key2++){a[_key2]=arguments[_key2];}return function(){a.forEach(function(b){return b();});};};
exports.objectKlassEquals=function(a,b){return null!==a?Object.getPrototypeOf(a).constructor.name===b.name:!1;};
exports.registerNestedElementResolver=function(a,b,c,f){return a.registerNodeTransform(b,function(d){a:{var e=d.getChildren();for(var h=0;h<e.length;h++){if(e[h]instanceof b){e=null;break a;}}for(e=d;null!==e;){if(h=e,e=e.getParent(),e instanceof b){e={child:h,parent:e};break a;}}e=null;}if(null!==e){var _e=e,m=_e.child,k=_e.parent;if(m.is(d)){f(k,d);d=m.getNextSiblings();e=d.length;k.insertAfter(m);if(0!==e){h=c(k);m.insertAfter(h);for(var l=0;l<e;l++){h.append(d[l]);}}k.canBeEmpty()||0!==k.getChildrenSize()||k.remove();}}});};
exports.removeClassNamesFromElement=function(a){for(var _len3=arguments.length,b=new Array(_len3>1?_len3-1:0),_key3=1;_key3<_len3;_key3++){b[_key3-1]=arguments[_key3];}b.forEach(function(c){var _a$classList2;"string"===typeof c&&(_a$classList2=a.classList).remove.apply(_a$classList2,c.split(" "));});};}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @fullSyntaxTransform
* @generated
* @noflow
* @nolint
* @oncall lexical_web_text_editor
* @preserve-invariant-messages
* @preserve-whitespace
* @preventMunge
 */__d("useLexicalEditable.prod",["LexicalComposerContext","react"],(function $module_useLexicalEditable_prod(global,require,requireDynamic,requireLazy,module,exports){
"use strict";var c_react;var k=c_react||(c_react=require("react")),l="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement?k.useLayoutEffect:k.useEffect;function m(a){var _b$useLexicalComposer=require("LexicalComposerContext").useLexicalComposerContext(),c=_b$useLexicalComposer[0],e=k.useMemo(function(){return a(c);},[c,a]),d=k.useRef(e.initialValueFn()),_k$useState=k.useState(d.current),n=_k$useState[0],g=_k$useState[1];l(function(){var p=e.initialValueFn,q=e.subscribe,f=p();d.current!==f&&(d.current=f,g(f));return q(function(h){d.current=h;g(h);});},[e,a]);return n;}
function r(a){return{initialValueFn:function initialValueFn(){return a.isEditable();},subscribe:function subscribe(c){return a.registerEditableListener(c);}};}module.exports=function(){return m(r);};}),null);
__d("lengthInUTF8Bytes",[],(function(a,b,c,d,e,f){"use strict";function g(a){var b=new TextEncoder();return b.encode(a).length}function h(a){var b=encodeURIComponent(a).match(/%[89ABab]/g);return a.length+(b?b.length:0)}a=function(){if(typeof TextEncoder==="undefined")return h;else return g}();f["default"]=a}),66);